language: php

notifications:
  on_success: never
  on_failure: change

branches:
   only:
     - master

php:
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/build.sh

script: phpunit
